services:
    web:
        image: nginx:latest
        container_name: web-server
        ports:
            - "80:80"
            - "443:443"
        command: ["sh", "-c", "nginx -g 'daemon off;' || tail -f /dev/null"]
        volumes:
            - ./nginx/ssl:/etc/nginx/ssl
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/nginx-app1.conf:/etc/nginx/nginx-app1.conf:ro
            - ./../app:/app:ro
